### ISSUE TITLE
Inventory Restore gives creative to survival players

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#269]
**Blast**: Not sure if this is intentional or not, but if you restore anything from the creative section in the survival world, the player is updated to creative mode (gmc). I found this out while trying to give myself my experience, which also does not appear to be functioning properly. Not action happens when you click the Experience word in chat.

**Comment by Pugabyte** [comment]
The gamemode part is working as intended. It has to restore the inventory to the right gamemode. Normal players dont have creative, so dont click it.

**Comment by Pugabyte** [comment]
```
[13:54:28] [Server thread/WARN]: [BNCore] Task #2750879 for BNCore v1.5 generated an exception
java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (1.1883389)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setExp(CraftPlayer.java:821) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        at me.pugabyte.bncore.features.restoreinventory.RestoreInventoryCommand.lambda$onCommand$0(RestoreInventoryCommand.java:91) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
