### ISSUE TITLE
Fix Prism rollback crash

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#288]
```
[21:00:56] [WhatIs ThreadLockChecker/WARN]: The main thread failed to respond after 10 seconds
[21:00:57] [WhatIs ThreadLockChecker/WARN]: Possible cause: Prism
[21:00:57] [WhatIs ThreadLockChecker/WARN]: -------------------------------------
[21:00:57] [WhatIs ThreadLockChecker/WARN]: Name: Server thread | Id: 18 | Suspended: false | State: RUNNABLE | Owner: Minecraft
[21:00:57] [WhatIs ThreadLockChecker/WARN]:
[21:00:57] [WhatIs ThreadLockChecker/WARN]: Owned monitors:
[21:00:57] [WhatIs ThreadLockChecker/WARN]:  - com.mysql.jdbc.util.ReadAheadInputStream[White Alpha] at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:  - com.mysql.jdbc.JDBC4Connection[Gray Alpha] at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:  - com.mysql.jdbc.JDBC4Connection[Gray Alpha] at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:  - com.mysql.jdbc.JDBC4Connection[Gray Alpha] at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:  - com.mysql.jdbc.JDBC4Connection[Gray Alpha] at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:  - com.mysql.jdbc.JDBC4Connection[Gray Alpha] at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
[21:00:57] [WhatIs ThreadLockChecker/WARN]: Stack trace:
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at java.net.SocketInputStream.socketRead0(Native Method)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at java.net.SocketInputStream.read(SocketInputStream.java:171)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at java.net.SocketInputStream.read(SocketInputStream.java:141)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at me.botsko.prism.actionlibs.RecordingTask.updateRollbackDatabase(RecordingTask.java:410) [Prism]
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at me.botsko.prism.appliers.Preview.postProcess(Preview.java:435) [Prism]
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at me.botsko.prism.appliers.Preview$1.run(Preview.java:372) [Prism]
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:00:57] [WhatIs ThreadLockChecker/WARN]:     at java.lang.Thread.run(Thread.java:748)
[21:00:57] [WhatIs ThreadLockChecker/WARN]: -------------------------------------
[21:01:07] [WhatIs ThreadLockChecker/WARN]: The server thread is still not responding:
[21:01:08] [WhatIs ThreadLockChecker/ERROR]: Current loop line is:
[21:01:08] [WhatIs ThreadLockChecker/ERROR]:     at java.net.SocketInputStream.socketRead0(Native Method)
[21:01:08] [WhatIs ThreadLockChecker/ERROR]: This appears to be caused by Prism
[21:01:08] [WhatIs ThreadLockChecker/WARN]: The full stack trace of the main thread is as follows:
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at java.net.SocketInputStream.socketRead0(Native Method)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at java.net.SocketInputStream.read(SocketInputStream.java:171)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at java.net.SocketInputStream.read(SocketInputStream.java:141)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at me.botsko.prism.actionlibs.RecordingTask.updateRollbackDatabase(RecordingTask.java:410) [Prism]
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at me.botsko.prism.appliers.Preview.postProcess(Preview.java:435) [Prism]
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at me.botsko.prism.appliers.Preview$1.run(Preview.java:372) [Prism]
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:01:08] [WhatIs ThreadLockChecker/WARN]:     at java.lang.Thread.run(Thread.java:748)
```

**Comment by Pugabyte** [comment]
Attempted fix made, closing until issue appears
