### ISSUE TITLE
poof & poofhere confusion

### ISSUE THREAD

**Issue by Blast-MC** [Pugabyte/BearNation#409]
poof needs a full rewrite to differentiate between /poof and /poofhere. When a player runs a player sends a poofhere request, and the receiver does /tpaccept instead of /poofhere accept, it functions like a normal poof instead of poofhere.

**Comment by Pugabyte** [comment]
```[15:09:54] [Craft Scheduler Thread - 3436/WARN]: [BNCore] Plugin BNCore v1.6 generated an exception while executing task 14603403
com.dieselpoint.norm.DbException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'senderLocation' in 'field list'
	at com.dieselpoint.norm.Query.results(Query.java:312) ~[?:?]
	at me.pugabyte.bncore.models.poof.PoofService.getActivePoofs(PoofService.java:34) ~[?:?]
	at me.pugabyte.bncore.models.poof.PoofService.getActivePoofs(PoofService.java:27) ~[?:?]
	at me.pugabyte.bncore.features.commands.poof.PoofCommand.lambda$static$1(PoofCommand.java:34) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-282]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'senderLocation' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_162]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_162]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.15.2.jar:git-Paper-282]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.15.2.jar:git-Paper-282]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[patched_1.15.2.jar:git-Paper-282]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[patched_1.15.2.jar:git-Paper-282]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[patched_1.15.2.jar:git-Paper-282]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[patched_1.15.2.jar:git-Paper-282]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[patched_1.15.2.jar:git-Paper-282]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[patched_1.15.2.jar:git-Paper-282]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912) ~[patched_1.15.2.jar:git-Paper-282]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020) ~[patched_1.15.2.jar:git-Paper-282]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
	at com.dieselpoint.norm.Query.results(Query.java:279) ~[?:?]
	... 9 more
```
