### ISSUE TITLE
CustomEnchants wither error

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#423]
```
[20:13:23] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to CustomEnchantments v2.4c
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_15_R1.entity.CraftLargeFireball cannot be cast to org.bukkit.entity.LivingEntity
	at com.taiter.ce.Enchantments.Global.Wither.effect(Wither.java:50) ~[?:?]
	at com.taiter.ce.CEventHandler.handleBows(CEventHandler.java:234) ~[?:?]
	at com.taiter.ce.CEListener.EntityDamageByEntityEvent(CEListener.java:413) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor548.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-367]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-367]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-367]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-367]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:240) ~[patched_1.15.2.jar:git-Paper-367]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1008) ~[patched_1.15.2.jar:git-Paper-367]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:895) ~[patched_1.15.2.jar:git-Paper-367]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1063) ~[patched_1.15.2.jar:git-Paper-367]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1049) ~[patched_1.15.2.jar:git-Paper-367]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1045) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.EntityFireball.damageEntity(EntityFireball.java:187) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:808) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.World.a(World.java:879) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:532) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-367]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-367]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by Blast-MC** [comment]
Fixed with instanceof check
