### ISSUE TITLE
Error while adding custom recipe white_bed_color

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#479]
```[16:11:12] [Server thread/INFO]: [BNCore] Error while adding custom recipe bncore:custom_white_bed_color
[16:11:12] [Server thread/WARN]: java.lang.NullPointerException
[16:11:12] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.getChoiceList(ShapelessRecipe.java:317)
[16:11:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftShapelessRecipe.fromBukkitRecipe(CraftShapelessRecipe.java:33)
[16:11:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.addRecipe(CraftServer.java:1209)
[16:11:12] [Server thread/WARN]: 	at org.bukkit.Bukkit.addRecipe(Bukkit.java:728)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.features.recipes.CustomRecipes.addRecipe(CustomRecipes.java:48)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.features.recipes.CustomRecipes.bedDying(CustomRecipes.java:232)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.features.recipes.CustomRecipes.startup(CustomRecipes.java:35)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.framework.features.Features.lambda$register$2(Features.java:70)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.utils.Time$Timer.<init>(Time.java:35)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.framework.features.Features.register(Features.java:68)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.framework.features.Features.register(Features.java:53)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.framework.features.Features.lambda$registerAll$1(Features.java:47)
[16:11:12] [Server thread/WARN]: 	at java.lang.Iterable.forEach(Iterable.java:75)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.framework.features.Features.registerAll(Features.java:47)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.BNCore.lambda$onEnable$2(BNCore.java:181)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.utils.Time$Timer.<init>(Time.java:35)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.BNCore.lambda$onEnable$4(BNCore.java:178)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.utils.Time$Timer.<init>(Time.java:35)
[16:11:12] [Server thread/WARN]: 	at me.pugabyte.bncore.BNCore.onEnable(BNCore.java:174)
[16:11:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:11:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:11:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:11:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[16:11:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[16:11:12] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[16:11:12] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[16:11:12] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909)
[16:11:12] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

Started happening today, I have no idea why, I'm 99% sure I didn't change anything; this is the only commit in the recipes folder in months
![image](https://user-images.githubusercontent.com/12417961/97050218-fa895700-154a-11eb-9507-788373f83be8.png)

**Comment by WakkaFlocka239** [comment]
<img src=https://i.imgur.com/dUYJzuy.jpg>

Material choice is being ignored and using air instead, custom recipes have been disabled until this is fixed.
